In [1]:
import numpy as np
import scipy as sp

In [4]:
A = np.array([[1,0],[1,-2]])
A

array([[ 1,  0],
       [ 1, -2]])

In [7]:
v,w = np.linalg.eig(A)

In [8]:
v

array([-2.,  1.])

In [9]:
w

array([[0.        , 0.9486833 ],
       [1.        , 0.31622777]])

In [16]:
P = np.column_stack((w[0], w[1]))

In [17]:
P

array([[0.        , 1.        ],
       [0.9486833 , 0.31622777]])

In [19]:
Q = np.linalg.inv(P)
Q

array([[-0.33333333,  1.05409255],
       [ 1.        ,  0.        ]])

In [28]:
R1 = np.outer(P[:,0], Q[0,:])

In [29]:
R1

array([[-0.        ,  0.        ],
       [-0.31622777,  1.        ]])

In [30]:
R2 = np.outer(P[:,1], Q[1,:])

In [31]:
R2

array([[1.        , 0.        ],
       [0.31622777, 0.        ]])