In [3]:
import numpy as np
from numpy import linalg as la

In [4]:
A = np.array([[0.5,0.4],[-0.7,0.5]])
A

array([[ 0.5,  0.4],
       [-0.7,  0.5]])

In [5]:
w,v = la.eig(A)

In [6]:
w

array([0.5+0.52915026j, 0.5-0.52915026j])

In [9]:
v

array([[0.        -0.60302269j, 0.        +0.60302269j],
       [0.79772404+0.j        , 0.79772404-0.j        ]])

In [15]:
la.inv(v.transpose())

array([[ 0.        +0.8291562j, -0.        -0.8291562j],
       [ 0.62678317+0.j       ,  0.62678317+0.j       ]])

In [11]:
abs(w[0])

0.7280109889280518