In [113]:
import numpy as np

In [114]:
G = np.array([[1,0.2,0.1],[0.1,2,0.1],[0.3,0.1,3]])
G

array([[1. , 0.2, 0.1],
       [0.1, 2. , 0.1],
       [0.3, 0.1, 3. ]])

In [115]:
alpha = 1.2
gamma = 3
A = G.copy()
A[0][0] = 0
A[1][1] = 0
A[2][2] = 0
A_star = A * alpha
A_star

array([[0.  , 0.24, 0.12],
       [0.12, 0.  , 0.12],
       [0.36, 0.12, 0.  ]])

In [116]:
A = A_star * gamma
A

array([[0.  , 0.72, 0.36],
       [0.36, 0.  , 0.36],
       [1.08, 0.36, 0.  ]])

In [117]:
sigma = 0.01
b = np.zeros(3)
for i in range(3):
    b[i] = (alpha * gamma * sigma)/G[i][i]
b

array([0.036, 0.018, 0.012])

In [118]:
from numpy import linalg as la

In [119]:
w, v = la.eig(A_star)

In [120]:
np.abs(w[0])

0.3480686249894354

In [121]:
np.abs(w[1])

0.18641826010891793

In [122]:
np.abs(w[2])

0.18641826010891793